version: "3"

networks:
  dz7:
    driver: bridge

services:
  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/src/app
    networks:
      - dz7
  mysql:
    image: "mysql:5.7.28"
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABSE=sandbox
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - dz7
